create_clock -period 500.000 -name phi2 -waveform {0.000 250.000} [get_ports phi2]
set_input_delay -clock [get_clocks phi2] -clock_fall -min -add_delay 10.000 [get_ports {data_in[*]}]
set_input_delay -clock [get_clocks phi2] -clock_fall -max -add_delay 440.000 [get_ports {data_in[*]}]
set_input_delay -clock [get_clocks phi2] -clock_fall -min -add_delay 200.000 [get_ports RES]
set_input_delay -clock [get_clocks phi2] -clock_fall -max -add_delay 300.000 [get_ports RES]
set_output_delay -clock [get_clocks phi2] -clock_fall -min -add_delay -10.000 [get_ports {address[*]}]
set_output_delay -clock [get_clocks phi2] -clock_fall -max -add_delay 351.000 [get_ports {address[*]}]
set_output_delay -clock [get_clocks phi2] -min -add_delay -10.000 [get_ports {data_out[*]}]
set_output_delay -clock [get_clocks phi2] -max -add_delay 111.000 [get_ports {data_out[*]}]
set_output_delay -clock [get_clocks phi2] -clock_fall -min -add_delay -10.000 [get_ports sync]
set_output_delay -clock [get_clocks phi2] -clock_fall -max -add_delay 351.000 [get_ports sync]
set_output_delay -clock [get_clocks phi2] -clock_fall -min -add_delay -10.000 [get_ports waitP]
set_output_delay -clock [get_clocks phi2] -clock_fall -max -add_delay 351.000 [get_ports waitP]
